### ISSUE TITLE
DSGE example

### ISSUE THREAD

**Issue by finmod** [mcreel/Econometrics#3]
Without going to MATLAB, the various estimation methods can be investigated directly with the current version of DSGE in Julia: https://github.com/FRBNY-DSGE/DSGE.jl .

The latest master does not test cleanly yet  with Julia 1.+ but they say in the README that this is imminent! 

Benchmarking between MATLAB and Julia can take place for some estimation methods.

**Comment by mcreel** [comment]
Thanks. I looked over that package some time ago. A PR that used the package in a way that could make an instructive contribution to the econometrics.pdf notes would be welcome. The main reason for existence of the Econometrics package is to support the lecture notes, so I typically only add packages to the dependencies if they are needed for use by examples that are discussed in the notes.
