### ISSUE TITLE
Having trouble with installation

### ISSUE THREAD

**Issue by alexboche** [mcreel/Econometrics#6]
I followed the installation instructions but then when I ran `using Econometrics`, it said it was precompiling the package and then it did not finish doing so for 5 minutes at which point I assumed it was not working. 

Here is a screenshot that shows the output from the last step of the installation: 

![image](https://user-images.githubusercontent.com/44827758/103608412-ed8cca80-4ee0-11eb-8da3-ed1ab39f63aa.png)

And here is a screenshot that shows the result of running the test you provide:
![image](https://user-images.githubusercontent.com/44827758/103608671-7c014c00-4ee1-11eb-9fa9-aee0ad3f1df3.png)

Any suggestions? Thanks!

**Comment by mcreel** [comment]
The econometrics code relies upon a lot of packages, which must all be compiled, so the first time you use it, compilation takes a while. If you don't see any error message, it just needs more time. Once that is done, subsequent use will be a lot faster.

**Comment by alexboche** [comment]
Ok it worked thanks. Actually it compiled almost immediately the second time.
